ignore:
  - "Koebenhavn H <-> Hamburg Hbf"
  - "København H <-> Hamburg Hbf"
  - "Kopenhagen Hbf <-> Hamburg Hbf"
  - "København H <-> Odense st"
  - "Kopenhagen Hbf <-> Odense st"
  - "Hamburg Hbf <-> Kolding st"
  - "Kopenhagen Hbf <-> Bramming st"
  - "Kopenhagen Hbf <-> Fredericia st"
  - "København H <-> Fredericia st"
  - "Bramming st <-> Kolding st"
  - "Bramming st <-> Fredericia st"
  - "Bramming st <-> Odense st"
  - "Odense st <-> Gelsted st"
  - "Odense st <-> Fredericia st"
  - "Korsoer st <-> Odense st"
  - "Slagelse St. (togbus) <-> Korsoer St. (togbus)"
  - "Slagelse st <-> Kopenhagen Hbf"
  - "Hamburg Hbf <-> Flensburg"
  - "Hamburg Hbf <-> Neumünster"
  - "Neumünster <-> Flensburg"
  - "Tinglev st <-> Fredericia st"
  - "Fredericia st <-> Flensburg"
  - "Flensburg <-> Fredericia St. (togbus)"
  - "Bramming st <-> Esbjerg st"
  - "Kopenhagen Hbf <-> Taastrup(v Koebenh.)"
  - "Taastrup(v Koebenh.) <-> Dybboelsbro st"
  - "Kopenhagen Hbf <-> Malmö Central"
  - "Odense st <-> Odense Sygehus st"
  - "København H <-> Helsingoer st"
  - "Hellerup st <-> Kopenhagen Hbf"
  - "Hellerup st <-> Dybboelsbro st"
  - "Dybboelsbro st <-> Koebenhavn Syd"
  - "Valby(Koebenhavn) <-> Dybboelsbro st"
  - "Dybboelsbro st <-> Noerreport st"
  - "Kopenhagen Hbf <-> Valby(Koebenhavn)"
  - "Noerreport st <-> Kopenhagen Hbf"
  - "Kopenhagen Hbf <-> Oesterport st"
  - "Berlin Hbf <-> Hamburg Hbf"
  - "Malmö Central <-> Stockholm Central"
  - "Linköping Central <-> Malmö Central"
  - "Göteborg Central <-> Malmö Central"
  - "Stockholm Central <-> Göteborg Central"
  - "Oslo S <-> Göteborg Central"
  - "Hamburg-Harburg <-> Stade"
  - "Stade <-> Hamburg Hbf"
  - "Hamburg Flughafen/Airport <-> Hamburg-Ohlsdorf"
  - "Wandsbeker Chaussee <-> Hamburg-Ohlsdorf"
  - "Hamburg-Poppenbüttel <-> Hamburg Hbf"
  - "Hamburg-Ohlsdorf <-> Hamburg-Poppenbüttel"
  - "Hamburg Wandsbeker Chaussee <-> Hamburg-Ohlsdorf"
  - "Noerreport st <-> København H"
  - "Oesterport st <-> København H"
  - "Dybboelsbro st <-> Oesterport st"
  - "Hannover Hbf <-> Hamburg Hbf"
  - "Hamburg-Harburg <-> Hamburg Hbf"
  - "Hamburg-Harburg <-> Hamburg-Altona"
  - "Leer (Ostfriesl) <-> Bremen Hbf"
  - "Groningen CS Hoofdstation <-> Leer (Ostfriesl)" # Not an actual train
  - "Bremen Hbf <-> Hamburg Hbf"
  - "Berlin Hbf <-> Leipzig Hbf"
  - "Berlin Südkreuz <-> Leipzig Hbf"
  - "Berlin Südkreuz <-> Frankfurt(Main)Hbf"
  - "Wuppertal Hbf <-> Hannover Hbf"
  - "Hamburg Hbf <-> Hamburg-Altona"
  - "Hamburg Hbf <-> Würzburg Hbf"
  - "Hamburg Hbf <-> Karlsruhe Hbf"
  - "Hamburg Hbf <-> Pinneberg"
  - "Würzburg Hbf <-> Aschaffenburg Hbf"
  - "Aschaffenburg Hbf <-> Köln Messe/Deutz Gl.11-12"
  - "Frankfurt(Main)Hbf <-> Aschaffenburg Hbf"
  - "Köln Messe/Deutz <-> Frankfurt(Main)Hbf"
  - "Wuppertal Hbf <-> Köln Messe/Deutz"
  - "Frankfurt(Main)Hbf <-> Köln Hbf"
  - "Karlsruhe Hbf <-> Köln Hbf"
  - "Mannheim Hbf <-> Karlsruhe Hbf"
  - "Frankfurt(Main)Hbf <-> Mannheim Hbf"
  - "Karlsruhe Hbf <-> Frankfurt(Main)Hbf"
  - "Karlsruhe Hbf <-> Leipzig Hbf"
  - "Leipzig, Apelstr./Historischer Betriebshof <-> Leipzig, Hauptbahnhof/Westseite"
  - "Leipzig, Apelstr./Historischer Betriebshof <-> Leipzig, Apelstr./Historischer Betriebshof"
  - "Zürich HB <-> München Hbf"
  - "Zürich HB <-> Luzern"
  - "Luzern <-> Interlaken Ost, Bahnhof"
  - "Bern <-> Interlaken Ost, Bahnhof"
  - "Bern <-> Visp"
  - "Visp <-> Thun, Bahnhof"
  - "Thun, Bahnhof <-> Bern"
  - "Zürich HB <-> Bern"
  - "4589983" # ./gpx/ice/berlin-mannheim-alt.gpx
  - "3297018" # Another Berlin Mannheim
  - "3667944" # ./gpx/ice/kassel-stuttgart.gpx
  - "4826446" # EC 8
  - "4381295" # Deutz to Hamburg, already covered
  - "4367102" # Köln to Dortmund
  - "3656016" # ./gpx/ice/darmstadt-mannheim.gpx
  - "3308080" # ./gpx/ice/stendal-uelzen.gpx"
  - "3649643" # HH to Frankfurt duplicate
  - "3555855" # ./gpx/ice/munich-würzburg.gpx
  - "3284861" # HH to Mannheim again
  - "2699465" # My first time on an ICE! Though it is a duplicate
  - "5329722" # ICE Erfurt to Leipzig
  - "5332553" # ICE Nürnberg to Munich
  - "5337653" # ICE Munich to Düsseldorf

routes:
  - "./gpx/ice/hh-b.gpx"
  - "./gpx/ice/hh-hannover.gpx"
  - "./gpx/ice/hh-hannover-2.gpx"
  - "./gpx/ice/berlin-leipzig.gpx"
  - "./gpx/ice/berlin-leipzig-alt.gpx"
  - "./gpx/ice/leipzig-frankfurt.gpx"
  - "./gpx/ice/berlin-mannheim-alt.gpx"
  - "./gpx/ice/köln-dortmund.gpx"
  - "./gpx/ice/wuppertal-hannover.gpx"
  - "./gpx/ice/hamburg-würzburg.gpx"
  - "./gpx/ice/kassel-stuttgart.gpx"
  - "./gpx/ice/darmstadt-mannheim.gpx"
  - "./gpx/ice/stendal-uelzen.gpx"
  - "./gpx/ice/munich-würzburg.gpx"
  - "./gpx/ice/würzburg-aschaffenburg.gpx"
  - "./gpx/ice/frankfurt-karlsruhe-alt.gpx"
  - "./gpx/ice/köln-frankfurt.gpx"
  - "./gpx/ice/munich-düsseldorf.gpx"
  - "./gpx/x2/stockholm.gpx"
  - "./gpx/x2/stockholm-gothenburg.gpx"
  - "./gpx/x2/gothenburg-diverted.gpx"
  - "./gpx/ec/cph-hh.gpx"
  - "./gpx/ec/ec8.gpx"
  - "./gpx/ec/ece-zürich-münchen.gpx"
  - "./gpx/ir/luzern.gpx"
  - "./gpx/ic/bramming-fredericia.gpx"
  - "./gpx/ic/fredericia-middelfart.gpx"
  - "./gpx/ic/over-roskilde.gpx"
  - "./gpx/ic/aarhus.gpx"
  - "./gpx/ic/karlsruhe-leipzig.gpx"
  - "./gpx/ic/interlaken-ost-to-bern.gpx"
  - "./gpx/ic/visp-bern.gpx"
  - "./gpx/ic/zürich-bern.gpx"
  - "./gpx/re/altona-niebüll.gpx"
  - "./gpx/re/oslo.gpx"
  - "./gpx/re/stade.gpx"
  - "./gpx/re/leer-bremen.gpx"
  - "./gpx/re/bremen-hamburg.gpx"
  - "./gpx/re/roskilde-jyderup.gpx"
  - "./gpx/re/hh-neumünster.gpx"
  - "./gpx/rb/gransee-berlin.gpx"
  - "./gpx/rb/cph-malmö.gpx"
  - "./gpx/rb/neg1.gpx"
  - "./gpx/rb/neg2.gpx"
  - "./gpx/rb/odense-sygehus.gpx"
  - "./gpx/rb/cph-elsinore.gpx"
  - "./gpx/rb/gardemoen-drammen.gpx"
  - "./gpx/rb/amsterdam-business.gpx"
  - "./gpx/s/frederikssund.gpx"
  - "./gpx/s/hamburg-airport.gpx"
  - "./gpx/s/poppenbüttel.gpx"
  - "./gpx/tram/nice.gpx"
  - "./gpx/special/KVV - Schlossgartenbahn (2,6km).gpx"
  - "./gpx/special/LVB 21E - {Rundfahrt} (7.3km).gpx"
  - "./gpx/special/panorama-express.gpx"
