ignore:
  - "Koebenhavn H <-> Hamburg Hbf"
  - "København H <-> Hamburg Hbf"
  - "Kopenhagen Hbf <-> Hamburg Hbf"
  - "København H <-> Odense st"
  - "Kopenhagen Hbf <-> Odense st"
  - "Hamburg Hbf <-> Kolding st"
  - "Kopenhagen Hbf <-> Bramming st"
  - "Kopenhagen Hbf <-> Fredericia st"
  - "København H <-> Fredericia st"
  - "Bramming st <-> Kolding st"
  - "Bramming st <-> Fredericia st"
  - "Bramming st <-> Odense st"
  - "Odense st <-> Gelsted st"
  - "Odense st <-> Fredericia st"
  - "Korsoer st <-> Odense st"
  - "Slagelse St. (togbus) <-> Korsoer St. (togbus)"
  - "Slagelse st <-> Kopenhagen Hbf"
  - "Hamburg Hbf <-> Flensburg"
  - "Hamburg Hbf <-> Neumünster"
  - "Neumünster <-> Flensburg"
  - "Tinglev st <-> Fredericia st"
  - "Fredericia st <-> Flensburg"
  - "Flensburg <-> Fredericia St. (togbus)"
  - "Bramming st <-> Esbjerg st"
  - "Kopenhagen Hbf <-> Taastrup(v Koebenh.)"
  - "Taastrup(v Koebenh.) <-> Dybboelsbro st"
  - "Kopenhagen Hbf <-> Malmö Central"
  - "Odense st <-> Odense Sygehus st"
  - "København H <-> Helsingoer st"
  - "Hellerup st <-> Kopenhagen Hbf"
  - "Hellerup st <-> Dybboelsbro st"
  - "Dybboelsbro st <-> Koebenhavn Syd"
  - "Valby(Koebenhavn) <-> Dybboelsbro st"
  - "Dybboelsbro st <-> Noerreport st"
  - "Kopenhagen Hbf <-> Valby(Koebenhavn)"
  - "Noerreport st <-> Kopenhagen Hbf"
  - "Kopenhagen Hbf <-> Oesterport st"
  - "Berlin Hbf <-> Hamburg Hbf"
  - "Malmö Central <-> Stockholm Central"
  - "Linköping Central <-> Malmö Central"
  - "Göteborg Central <-> Malmö Central"
  - "Stockholm Central <-> Göteborg Central"
  - "Oslo S <-> Göteborg Central"
  - "Hamburg-Harburg <-> Stade"
  - "Stade <-> Hamburg Hbf"
  - "Hamburg Flughafen/Airport <-> Hamburg-Ohlsdorf"
  - "Wandsbeker Chaussee <-> Hamburg-Ohlsdorf"
  - "Hamburg-Poppenbüttel <-> Hamburg Hbf"
  - "Hamburg-Ohlsdorf <-> Hamburg-Poppenbüttel"
  - "Hamburg Wandsbeker Chaussee <-> Hamburg-Ohlsdorf"
  - "Noerreport st <-> København H"
  - "Oesterport st <-> København H"
  - "Dybboelsbro st <-> Oesterport st"
  - "Hannover Hbf <-> Hamburg Hbf"
  - "Hamburg-Harburg <-> Hamburg Hbf"
  - "Hamburg-Harburg <-> Hamburg-Altona"
  - "Leer (Ostfriesl) <-> Bremen Hbf"
  - "Groningen CS Hoofdstation <-> Leer (Ostfriesl)" # Not an actual train
  - "Bremen Hbf <-> Hamburg Hbf"

routes:
  - "./gpx/ice/hh-b.gpx"
  - "./gpx/ice/hh-hannover.gpx"
  - "./gpx/x2/stockholm.gpx"
  - "./gpx/x2/stockholm-gothenburg.gpx"
  - "./gpx/x2/gothenburg-diverted.gpx"
  - "./gpx/ec/cph-hh.gpx"
  - "./gpx/ic/bramming-fredericia.gpx"
  - "./gpx/ic/fredericia-middelfart.gpx"
  - "./gpx/ic/over-roskilde.gpx"
  - "./gpx/ic/aarhus.gpx"
  - "./gpx/re/altona-niebüll.gpx"
  - "./gpx/re/oslo.gpx"
  - "./gpx/re/stade.gpx"
  - "./gpx/re/leer-bremen.gpx"
  - "./gpx/re/bremen-hamburg.gpx"
  - "./gpx/rb/cph-malmö.gpx"
  - "./gpx/rb/neg1.gpx"
  - "./gpx/rb/neg2.gpx"
  - "./gpx/rb/odense-sygehus.gpx"
  - "./gpx/rb/cph-elsinore.gpx"
  - "./gpx/rb/gardemoen-drammen.gpx"
  - "./gpx/s/frederikssund.gpx"
  - "./gpx/s/hamburg-airport.gpx"
  - "./gpx/s/poppenbüttel.gpx"